name: UpdateRSS
on:
  schedule:
    - cron:  '0 0 * * *'    # 国际标准时间0点（北京时间早上8点发）
  workflow_dispatch:
  
jobs:
  push:
      runs-on: ubuntu-latest

      steps:
      - name: checkout defult branch 
        uses: actions/checkout@v2 # Checking out the repo         

      - name: Install dependecies
        uses: VaultVulp/action-pipenv@v2.0.1
        with:          
          command: install -d # Install all dependencies, including development ones     
          
      - name: Build
        env:
            MY_HEADERS: ${{ secrets.MY_HEADERS }}
            MY_HOST: ${{ secrets.MY_HOST }}
            MY_DATA: ${{ secrets.MY_DATA }}
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: run build
          
      - name: Commit and push if changed   # 更新README.md
        run: |
          git diff
          git config --global user.email "65473527+15x15G@users.noreply.github.com"
          git config --global user.name "15x15G"
          git add README.md
          git add docs
          git commit --amend -m "Auto Updated: `date +'%Y-%m-%d %H:%M:%S'`"
          git push -f
